server:
  port: 8875
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: 'shopping-seller-ms'
  datasource:
    username: root
    password: 960815
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource

 