server:
  port: 8086
spring:
  data:
    solr:
      host: http://localhost/solr
  datasource:
    username: root
    password: 960815
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource