server:
  port: 8876
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: 'shopping-sellergoods-ms'
  datasource:
    username: root
    password: 15995123
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
pagehelper:
  helper-dialect: mysql
  reasonable: true
file:
  staticAccessPath: '/upload/**'
  uploadFolder: 'E:\\ProgramData\\Java\\tempData\\file'
 