spring:
  application:
    name: 'shopping-pojo'
  datasource:
    username: root
    password: 15995123
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helper-dialect: mysql
  reasonable: true


 